# -*- coding: utf-8 -*-
"""Copy of 700-700(03).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10OVAPUByd2YP_2fHLc0Uut45sWM-Ivwf
"""

from google.colab import drive
drive.mount('/content/drive')

import os

!pip install keras

!pip show tensorflow

!pip install tensorflow

import numpy as np
import pandas as pd
import os
import keras
from keras import layers
#from keras import ops
import matplotlib.pyplot as plt

!pip install lime

!pip install shap

from PIL import Image
from sklearn.model_selection import train_test_split
import random
import tensorflow as tf
from tensorflow.keras import layers, models
from sklearn.metrics import classification_report, confusion_matrix
from matplotlib import pyplot as plt
import lime
from lime import lime_image
import shap
from tensorflow.keras.applications import VGG16  # Replace with your pre-trained model if not VGG16
from tensorflow.keras.preprocessing.image import img_to_array, load_img
import cv2  # Import cv2 for image processing
from matplotlib import pyplot as plt
from tensorflow.keras.applications.vgg16 import preprocess_input
from tensorflow.keras.preprocessing import image
from skimage.transform import resize
from tensorflow.keras.models import Model
# from tf_keras_vis.gradcam import Gradcam

!pip install imutils
from imutils import paths
import matplotlib.pyplot as plt
import argparse
import os
import keras
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.layers import Conv1D,Conv2D,MaxPooling1D,MaxPooling2D
from keras.layers import Activation,LSTM,GRU,Reshape
from keras.layers import BatchNormalization
from tensorflow.keras.applications import VGG16,VGG19,ResNet50,DenseNet121,DenseNet169,Xception
from tensorflow.keras.applications.inception_v3 import InceptionV3
from keras.layers import Dense, GlobalAveragePooling2D
from tensorflow.keras.layers import AveragePooling2D
from tensorflow.keras.layers import Dropout
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Input
from tensorflow.keras import regularizers
from tensorflow.keras.models import Model
from keras.models import Sequential
from tensorflow.keras.optimizers import Adam
from sklearn.model_selection import KFold
import numpy as np
from tensorflow.keras.utils import to_categorical
from sklearn.preprocessing import LabelBinarizer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MultiLabelBinarizer
from sklearn.preprocessing import LabelEncoder
from keras import optimizers
from keras.callbacks import ModelCheckpoint, EarlyStopping, ReduceLROnPlateau
from tensorflow.keras.losses import binary_crossentropy,categorical_crossentropy,sparse_categorical_crossentropy
from tensorflow.keras.utils import to_categorical
from keras.layers import LSTM
!pip install keras_metrics
import keras_metrics

import os
Data_Dir = "/content/drive/MyDrive/700-700_New_Dataset"

TBimages = os.listdir(Data_Dir+"/Tuberculosis")
Nimages =  os.listdir(Data_Dir+"/Normal")

import os
import cv2
import numpy as np
import matplotlib.pyplot as plt
from skimage import transform as skimage_transform

# Assuming Data_Dir, Nimages, and TBimages are defined

def plotter(i):
    Nimages = os.listdir(os.path.join(Data_Dir, "Normal"))
    TBimages = os.listdir(os.path.join(Data_Dir, "Tuberculosis"))

    normal_path = os.path.join(Data_Dir, "Normal", Nimages[i])
    tb_path = os.path.join(Data_Dir, "Tuberculosis", TBimages[i])

    normal = cv2.imread(normal_path)
    tb = cv2.imread(tb_path)

    if normal is not None and tb is not None:
        # Resize images using skimage
        normal = skimage_transform.resize(normal, (224, 224, 3), mode='reflect', anti_aliasing=True)
        tb = skimage_transform.resize(tb, (224, 224, 3), mode='reflect', anti_aliasing=True)

        # Convert the images to uint8 before concatenating
        normal = (normal * 255).astype(np.uint8)
        tb = (tb * 255).astype(np.uint8)

        # Concatenate images horizontally
        pair = np.concatenate((normal, tb), axis=1)

        # Display the images
        print("Normal Chest X-Ray Vs Tuberculosis Chest X-Ray")
        plt.figure(figsize=(10, 5))  # Adjust the size for better visualization
        plt.imshow(cv2.cvtColor(pair, cv2.COLOR_BGR2RGB))
        plt.axis('off')
        plt.show()
    else:
        print(f"Error loading images at index {i}")

# Plot first 5 image pairs
for i in range(5):
    plotter(i)

TBimages = len(os.listdir(os.path.join(Data_Dir+"/Tuberculosis")))
Nimages = len(os.listdir(os.path.join(Data_Dir+"/Normal")))
print("Length of Tuberculosis images:",TBimages)
print("Length of Normal images:",Nimages)

dataset = "/content/drive/MyDrive/700-700_New_Dataset"
args={}
args["dataset"]=dataset

!pip install imutils
import imutils
from imutils import paths

ipaths = list(paths.list_images(args["dataset"]))
data = []
labels = []

for ipath in ipaths:
    label = ipath.split(os.path.sep)[-2]  # Extract the label from the path
    image = cv2.imread(ipath)  # Read the image
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)  # Convert image to RGB
    image = cv2.resize(image, (224, 224))  # Resize image to 224x224

    data.append(image)  # Append the processed image to the data list
    labels.append(label)  # Append the label to the labels list

# Convert lists to numpy arrays once after the loop
data = np.array(data) / 255.0  # Normalize the image data
labels = np.array(labels)

print("Data shape:", data.shape)
print("Labels shape:", labels.shape)

import sklearn.preprocessing
from sklearn.preprocessing import LabelBinarizer # Import the LabelBinarizer class
import numpy as np
from tensorflow.keras.utils import to_categorical

LB = LabelBinarizer()  #Initialize label binarizer
labels = LB.fit_transform(labels)
labels = to_categorical(labels)
print(labels)

# split between Training and Test Image
XN_train, XN_test, YN_train, YN_test = train_test_split(data, labels, test_size=0.27,
                                                        random_state = np.random.randint(1,1000, 1)[0])

# Split between Training and Validation Images
X_train, X_test, Y_train, Y_test = train_test_split(XN_train, YN_train, test_size=0.22,
                                                    random_state = np.random.randint(1,1000, 1)[0])

# Number of Images in training and test images Network
print(" Training & Val Images in XN Train class:",XN_train.shape)
print(" Training & Val Images in YN Train class:",YN_train.shape)
print(" Training Images in X Train class:",X_train.shape)
print(" Training Images in Y Train class:",Y_train.shape)
print(" Val Images in X Test class:",X_test.shape)
print(" Val Images in Y Test class:",Y_test.shape)
print(" Test Images in XN Test class:",XN_test.shape)
print(" Test Images in YN Test class:",YN_test.shape)

#Distiller
#from tensorflow.keras.layers import ops
import keras

class Distiller(keras.Model):
    def __init__(self, student, teacher):
        super().__init__()
        self.teacher = teacher
        self.student = student

    def compile(
        self,
        optimizer,
        metrics,
        student_loss_fn,
        distillation_loss_fn,
        alpha=0.1,
        temperature=3,
    ):
        """Configure the distiller.

        Args:
            optimizer: Keras optimizer for the student weights
            metrics: Keras metrics for evaluation
            student_loss_fn: Loss function of difference between student
                predictions and ground-truth
            distillation_loss_fn: Loss function of difference between soft
                student predictions and soft teacher predictions
            alpha: weight to student_loss_fn and 1-alpha to distillation_loss_fn
            temperature: Temperature for softening probability distributions.
                Larger temperature gives softer distributions.
        """
        super().compile(optimizer=optimizer, metrics=metrics)
        self.student_loss_fn = student_loss_fn
        self.distillation_loss_fn = distillation_loss_fn
        self.alpha = alpha
        self.temperature = temperature

    def compute_loss(
        self, x=None, y=None, y_pred=None, sample_weight=None, allow_empty=False
    ):
        teacher_pred = self.teacher(x, training=False)
        student_loss = self.student_loss_fn(y, y_pred)

        distillation_loss = self.distillation_loss_fn(
            ops.softmax(teacher_pred / self.temperature, axis=1),
            ops.softmax(y_pred / self.temperature, axis=1),
        ) * (self.temperature**2)

        loss = self.alpha * student_loss + (1 - self.alpha) * distillation_loss
        return loss

    def call(self, x):
        return self.student(x)

#Create student and teacher models
import keras
import keras.layers as layers

# Create the teacher
teacher = keras.Sequential(
    [
        keras.Input(shape=(224, 224, 1)),
        layers.Conv2D(256, (3, 3), strides=(2, 2), padding="same"),
        layers.LeakyReLU(negative_slope=0.2),
        layers.MaxPooling2D(pool_size=(2, 2), strides=(1, 1), padding="same"),
        layers.Conv2D(512, (3, 3), strides=(2, 2), padding="same"),
        layers.Flatten(),
        layers.Dense(2),
    ],
    name="teacher",
)

# Create the student
student = keras.Sequential(
    [
        keras.Input(shape=(224, 224, 1)),
        layers.Conv2D(16, (3, 3), strides=(2, 2), padding="same"),
        layers.LeakyReLU(negative_slope=0.2),
        layers.MaxPooling2D(pool_size=(2, 2), strides=(1, 1), padding="same"),
        layers.Conv2D(32, (3, 3), strides=(2, 2), padding="same"),
        layers.Flatten(),
        layers.Dense(2),
    ],
    name="student",
)

# Clone student for later comparison
student_scratch = keras.models.clone_model(student)

!pip install my_module

# Define per-fold score containers for Test
acc_per_fold = []
loss_per_fold = []

acc_per_fold1 = []
loss_per_fold1 = []

# Define per-fold score containers for Train
acc_per_fold1 = []
loss_per_fold1 = []

acc_per_fold11 = []
loss_per_fold11 = []

# Define per-fold score containers for Train
acc_per_fold2 = []
loss_per_fold2 = []

acc_per_fold21 = []
loss_per_fold21 = []

# Merge inputs and targets
inputs = np.concatenate((X_train, X_test), axis=0)
targets = np.concatenate((Y_train, Y_test), axis=0)

# Define the K-fold Cross Validator
num_folds = 5

kfold = KFold(n_splits=num_folds,shuffle=True)

# Define some callbacks
pat = 10 #this is the number of epochs with no improvment after which the training will stop
verbosity = 1
early_stopping = EarlyStopping(monitor='val_loss', patience=pat, verbose=1)

# Train teacher as usual
teacher.compile(
    optimizer=keras.optimizers.Adam(learning_rate=0.0001),
    loss=keras.losses.BinaryCrossentropy(from_logits=True),
    metrics=[keras.metrics.BinaryAccuracy(name="accuracy")],
)

#checkpoint_filepath = "/tmp/checkpoint.weights.h5"
#checkpoint_callback = keras.callbacks.ModelCheckpoint(
    #checkpoint_filepath,
    #monitor="val_accuracy",
    #save_best_only=True,
    #save_weights_only=True,
#)

# Convert X_train and X_test to grayscale if they are color images
#if X_train.shape[-1] == 3:  # Check if X_train has 3 channels (color)
    #X_train_gray = tf.image.rgb_to_grayscale(X_train)
    #X_test_gray = tf.image.rgb_to_grayscale(X_test)
    #XN_test_gray = tf.image.rgb_to_grayscale(XN_test)
#else:
    #X_train_gray = X_train  # Keep as is if already grayscale
    #X_test_gray = X_test
    #XN_test_gray = XN_test

# Convert ALL input data to grayscale
# Assuming your images are in RGB format (if not, adjust accordingly)
X_train_gray = tf.image.rgb_to_grayscale(X_train)
X_test_gray = tf.image.rgb_to_grayscale(X_test)
XN_test_gray = tf.image.rgb_to_grayscale(XN_test)

# Update 'inputs' to use grayscale images
inputs = np.concatenate((X_train_gray, X_test_gray), axis=0)


# K-fold Cross Validation model evaluation
fold_no = 1
R=[]
for train, test in kfold.split(inputs, targets):

    print(f'Training for fold {fold_no} ...')
        # Convert the inputs for this fold to grayscale
    inputs_train_gray = inputs[train]
    inputs_test_gray = inputs[test]

    # Train the teacher model for this fold

    R.append(teacher.fit(inputs_train_gray, targets[train],batch_size=16,epochs=100,verbose=verbosity,
                     validation_data=(inputs_test_gray, targets[test]), callbacks=[early_stopping]))

    print('--------------------- Training Data-------------------------------')
    scores1 = teacher.evaluate(inputs_train_gray, targets[train], verbose=0)
    print(f'Score for fold {fold_no}: {teacher.metrics_names[0]} of {scores1[0]}; {teacher.metrics_names[1]} of {scores1[1]*100}%')
    acc_per_fold1.append(scores1[1] * 100)
    loss_per_fold1.append(scores1[0])

    print('-------------------- Validation Data-------------------------------')
    scores = teacher.evaluate(inputs_test_gray, targets[test], verbose=0)
    print(f'Score for fold {fold_no}: {teacher.metrics_names[0]} of {scores[0]}; {teacher.metrics_names[1]} of {scores[1]*100}%')
    acc_per_fold.append(scores[1] * 100)
    loss_per_fold.append(scores[0])

    print('--------------------- Test Data-------------------------------')
    scores2 = teacher.evaluate(XN_test_gray, YN_test, verbose=0)
    print(f'Score for fold {fold_no}: {teacher.metrics_names[0]} of {scores2[0]}; {teacher.metrics_names[1]} of {scores2[1]*100}%')
    acc_per_fold2.append(scores2[1] * 100)
    loss_per_fold2.append(scores2[0])

    # Increase fold number
    fold_no = fold_no + 1


print('-------------------- Training Data-------------------------------')
print('Score per fold')
for i in range(0, len(acc_per_fold1)):
  print('------------------------------------------------------------------------')
  print(f'> Fold {i+1} - Loss: {loss_per_fold1[i]} - Accuracy: {acc_per_fold1[i]}%')
  print('------------------------------------------------------------------------')
  print('Average scores for all folds:')
  print(f'> Accuracy: {np.mean(acc_per_fold1)} (+- {np.std(acc_per_fold1)})')
  print(f'> Loss: {np.mean(loss_per_fold1)}')
  print('------------------------------------------------------------------------')


print('-------------------- Validation Data-------------------------------')
print('Score per fold')
for i in range(0, len(acc_per_fold)):
  print('------------------------------------------------------------------------')
  print(f'> Fold {i+1} - Loss: {loss_per_fold[i]} - Accuracy: {acc_per_fold[i]}%')
  print('------------------------------------------------------------------------')
  print('Average scores for all folds:')
  print(f'> Accuracy: {np.mean(acc_per_fold)} (+- {np.std(acc_per_fold)})')
  print(f'> Loss: {np.mean(loss_per_fold)}')
  print('------------------------------------------------------------------------')


print('-------------------- Test Data-------------------------------')
print('Score per fold')
for i in range(0, len(acc_per_fold2)):
  print('------------------------------------------------------------------------')
  print(f'> Fold {i+1} - Loss: {loss_per_fold2[i]} - Accuracy: {acc_per_fold2[i]}%')
  print('------------------------------------------------------------------------')
  print('Average scores for all folds:')
  print(f'> Accuracy: {np.mean(acc_per_fold2)} (+- {np.std(acc_per_fold2)})')
  print(f'> Loss: {np.mean(loss_per_fold2)}')
  print('------------------------------------------------------------------------')


#history = teacher.fit(
    #x=X_train_gray,
    #y=Y_train,
    #batch_size=16,
    #epochs=100,
    #validation_data=(X_test_gray, Y_test),
    #callbacks=[checkpoint_callback],
#)

#teacher.load_weights(checkpoint_filepath)
#_, accuracy = teacher.evaluate(XN_test_gray, YN_test)

# Print the test accuracy
#print(f"Teacher Test accuracy: {round(accuracy * 100, 2)}%")

# Plot the training and validation loss for each fold
for fold in R:
    plt.plot(fold.history["loss"], label="train_loss")
    plt.plot(fold.history["val_loss"], label="val_loss")

#plt.plot(R.history["loss"], label="train_loss")
#plt.plot(R.history["val_loss"], label="val_loss")
plt.xlabel("Epochs")
plt.ylabel("Loss")
plt.title("Teacher Train and Validation Losses Over Epochs", fontsize=14)
plt.legend()
plt.grid()
plt.show()

# Define some callbacks
pat1 = 10     # this is the number of epochs with no improvment after which the training will stop
verbosity1 = 1
early_stopping1 = EarlyStopping(monitor='val_loss', patience=pat1, verbose=1)

# Initialize and compile distiller

import tensorflow.keras.backend as ops # Import the ops module


distiller = Distiller(student=student, teacher=teacher)
distiller.compile(
    optimizer=keras.optimizers.Adam(learning_rate=0.0001),
    metrics=[keras.metrics.BinaryAccuracy(name="accuracy")],
    student_loss_fn=keras.losses.BinaryCrossentropy(from_logits=True),
    distillation_loss_fn=keras.losses.KLDivergence(),
    alpha=0.1,
    temperature=10,
)

#checkpoint_filepath_student = "/tmp/checkpoint_student.weights1.h5"
#checkpoint_filepath_student = "/tmp/checkpoint_student_unique.weights.h5"
#checkpoint_callback = keras.callbacks.ModelCheckpoint(
    #checkpoint_filepath_student,
    #monitor="val_accuracy",
    #save_best_only=True,
    #save_weights_only=True,
#)

# Convert X_train and X_test to grayscale if they are color images
#if X_train.shape[-1] == 3:  # Check if X_train has 3 channels (color)
    #X_train_gray = tf.image.rgb_to_grayscale(X_train)
    #X_test_gray = tf.image.rgb_to_grayscale(X_test)
    #XN_test_gray = tf.image.rgb_to_grayscale(XN_test)
#else:
    #X_train_gray = X_train  # Keep as is if already grayscale
    #X_test_gray = X_test
    #XN_test_gray = XN_test

# Convert ALL input data to grayscale
# Assuming your images are in RGB format (if not, adjust accordingly)
#X_train_gray = tf.image.rgb_to_grayscale(X_train)
#X_test_gray = tf.image.rgb_to_grayscale(X_test)
#XN_test_gray = tf.image.rgb_to_grayscale(XN_test)

# Update 'inputs' to use grayscale images
#inputs = np.concatenate((X_train_gray, X_test_gray), axis=0)


# K-fold Cross Validation model evaluation
fold_no1 = 1
R1=[]
for train, test in kfold.split(inputs, targets):

    print(f'Training for fold {fold_no1} ...')
    R1.append(distiller.fit(inputs[train], targets[train],batch_size=16,epochs=100,verbose=verbosity1,
                     validation_data=(inputs[test], targets[test]), callbacks=[early_stopping1]))

    print('--------------------- Training Data-------------------------------')
    scores11 = distiller.evaluate(inputs[train], targets[train], verbose=0)
    print(f'Score for fold {fold_no1}: {distiller.metrics_names[0]} of {scores11[0]}; {distiller.metrics_names[1]} of {scores11[1]*100}%')
    acc_per_fold11.append(scores11[1] * 100)
    loss_per_fold11.append(scores11[0])

    print('-------------------- Validation Data-------------------------------')
    scores1 = distiller.evaluate(inputs[test], targets[test], verbose=0)
    print(f'Score for fold {fold_no1}: {distiller.metrics_names[0]} of {scores1[0]}; {distiller.metrics_names[1]} of {scores1[1]*100}%')
    acc_per_fold1.append(scores1[1] * 100)
    loss_per_fold1.append(scores1[0])

    print('--------------------- Test Data-------------------------------')
    scores21 = distiller.evaluate(XN_test_gray, YN_test, verbose=0)
    print(f'Score for fold {fold_no1}: {distiller.metrics_names[0]} of {scores21[0]}; {distiller.metrics_names[1]} of {scores21[1]*100}%')
    acc_per_fold21.append(scores21[1] * 100)
    loss_per_fold21.append(scores21[0])

    # Increase fold number
    fold_no1 = fold_no1 + 1


print('-------------------- Training Data-------------------------------')
print('Score per fold')
for i in range(0, len(acc_per_fold11)):
  print('------------------------------------------------------------------------')
  print(f'> Fold {i+1} - Loss: {loss_per_fold11[i]} - Accuracy: {acc_per_fold11[i]}%')
  print('------------------------------------------------------------------------')
  print('Average scores for all folds:')
  print(f'> Accuracy: {np.mean(acc_per_fold11)} (+- {np.std(acc_per_fold11)})')
  print(f'> Loss: {np.mean(loss_per_fold11)}')
  print('------------------------------------------------------------------------')


print('-------------------- Validation Data-------------------------------')
print('Score per fold')
for i in range(0, len(acc_per_fold1)):
  print('------------------------------------------------------------------------')
  print(f'> Fold {i+1} - Loss: {loss_per_fold1[i]} - Accuracy: {acc_per_fold1[i]}%')
  print('------------------------------------------------------------------------')
  print('Average scores for all folds:')
  print(f'> Accuracy: {np.mean(acc_per_fold1)} (+- {np.std(acc_per_fold1)})')
  print(f'> Loss: {np.mean(loss_per_fold1)}')
  print('------------------------------------------------------------------------')


print('-------------------- Test Data-------------------------------')
print('Score per fold')
for i in range(0, len(acc_per_fold21)):
  print('------------------------------------------------------------------------')
  print(f'> Fold {i+1} - Loss: {loss_per_fold21[i]} - Accuracy: {acc_per_fold21[i]}%')
  print('------------------------------------------------------------------------')
  print('Average scores for all folds:')
  print(f'> Accuracy: {np.mean(acc_per_fold21)} (+- {np.std(acc_per_fold21)})')
  print(f'> Loss: {np.mean(loss_per_fold21)}')
  print('------------------------------------------------------------------------')



# Train and evaluate student following normal Keras training procedure

#history1 = distiller.fit(
    #x=X_train_gray,
    #y=Y_train,
    #batch_size=16,
    #epochs=100,
    #validation_data=(X_test_gray, Y_test),
    #callbacks=[checkpoint_callback],
#)

#distiller.load_weights(checkpoint_filepath_student)
#results = distiller.evaluate(XN_test_gray, YN_test)
#accuracy = results[2]
# Print the test accuracy
#print(f"Student Test accuracy: {round(accuracy * 100, 2)}%")

# Plot the training and validation loss for each fold
for fold in R1:
    plt.plot(fold.history["loss"], label="train_loss")
    plt.plot(fold.history["val_loss"], label="val_loss")

#plt.plot(R1.history["loss"], label="train_loss")
#plt.plot(R1.history["val_loss"], label="val_loss")
plt.xlabel("Epochs")
plt.ylabel("Loss")
plt.title("Student Train and Validation Losses Over Epochs", fontsize=14)
plt.legend()
plt.grid()
plt.show()